### ISSUE TITLE
Request: guidelines/tutorial

### ISSUE THREAD

**Issue by ozum** [hapipal/discuss#1]
Hi,

Thank you for `hapipal`. I read README and API docs of several hapipal repos. Although I like the idea of freedom provided by `hapi` very much, it is good to have organization practices like `haute-couture` in case needed, which I definitely need and prefer some collaborative effort instead of my own. 

I'm trying to use hapipal modules/repos, but it is not easy to swallow whole picture together.

Could you please add some guidelines or tutorial besides ["Best Practices"](https://hapipal.com/best-practices) in hapipal.com.

Particularly a tutorial covering topics below:
* Contains a few user-land plugins together.
* Considers best practices,
* How `haute-couture`, `schwifty`, swagger and hapipal boilerplate can be used together and relation between them (i.e. what file goes where and does what?)
* [EDIT] Some explanation about how to use `haute-couture` and `glue` together like in hapipal boilerplate.
* Includes a bare minimum authentication.
* To cover sharing of authentication, a plugin which uses authentication and a plugin which does not.

I'm aware that it is a daunting task to cover those in a tutorial, but I think it helps people starting to use `hapipal`.

Kind regards,

**Comment by devinivy** [comment]
Hey there.  We also see the need for a tutorial that helps illustrate the "whole picture" (as you said), especially given that hapi pal is so modular and leans on other ecosystems/libraries to do what they do best.  I think different folks will be interested in different tutorial contents depending on what they're trying to build and what familiarity they already have with hapijs.

That said, we actually have decided on some baseline functionality, and wrote a tutorial around it!  It hasn't been linked on the site yet, but it can be found here: https://hapipal.com/getting-started.  It is a step-by-step guide to build [this API](https://github.com/hapipal/examples/tree/master/paldo-riddles) for serving riddles, backed by a SQL database, and it explains lots of the hapi pal tooling and the structure of the boilerplate.  We're definitely open to feedback on it!  But it covers use of haute-couture, glue, schwifty, and swagger using the pal boilerplate, so it sounds very similar to what you're looking for.  I could imagine a "part two" that goes into implementing something like auth—but really, once you get the hang of pal, then you should be able to apply existing knowledge about hapijs auth that's already out there!  At least that's our goal 🙂

**Comment by ozum** [comment]
Thanks, that's great.

**Comment by YoannMa** [comment]
In mean time you could also check out this "boilerplate" https://github.com/mattboutet/user-pal

**Comment by ozum** [comment]
@devinivy, I read ["Getting Started"](https://hapipal.com/getting-started) and it is a great article and covers most of the points I suggested. I'm eager to see it's link put on the web site.

@YoannMa, thanks, I'll skimmed your boilerplate, seems very useful. I will try it.

**Comment by devinivy** [comment]
The link is now up (see the top navigation on https://hapipal.com), with some recent adjustments to the tutorial.

**Comment by ozum** [comment]
Kudos to article author, clean, nice and covering article.

**Comment by devinivy** [comment]
That would be @zemccartney :)

**Comment by zemccartney** [comment]
glad it was helpful, @ozum 

and @devinivy 's of course underselling himself here; he also shouldered a chunk of the work on that piece :) 

thanks for checking things out and for the suggestions 🙏

**Comment by ozum** [comment]
I'm playing with hpal right now, thanks to @zemccartney's article.

Also @devinivy gave me a thoughtful answer previously [here](https://github.com/hapijs/discuss/issues/616#issuecomment-361000590). At that time I'm unaware of `haute-couture` and `schwifty` and trying to build my hapi code organization. While reading [best practices](https://hapipal.com/best-practices), one article's tone reminded me that answer. I went back and checked the answer, and realized he answered it.

If it wasn't lack of my attention, I think you should consider to promote hapi pal more aggressively.
