### ISSUE TITLE
Travis config

### ISSUE THREAD

**Issue by YoannMa** [hapipal/discuss#5]
Should we do something similar to https://github.com/hapijs/ci-config-travis as well for Hapipal ?

**Comment by Nargonath** [comment]
Yeah I wondered the same thing when I updated confidence since I had to update the travis configuration. That could be worth doing IMO even though there are less repo in hapipal than there are in hapi org.

**Comment by devinivy** [comment]
I'm into it!  Let's do that before updating any more travis configs.  Will try to get it going tonight or tomorrow 👍

**Comment by devinivy** [comment]
https://github.com/hapipal/ci-config-travis

Here it is!  I think it should be all set, but let me know if you run into any issues with it.
 - All repos will use `node_js.yml`.
 - Plugins, etc. that are tested against multiple hapi versions will additionally include `hapi_all.yml`.
 - Modules that test against all operating systems (in particular hpal) will additionally include `os_all.yml`.

**Comment by YoannMa** [comment]
Great thanks, I'll update my PR hapipal/lalalambda#13 soon to reflect this change.
